<a href="https://colab.research.google.com/github/Asma-malica/DL/blob/main/DL_TitanicNeuralNetwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
data_train = pd.read_csv('/content/train.csv')
data_test = pd.read_csv('/content/test.csv')

In [ ]:
data_train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
data_train.fillna(method = "Bfill" ,inplace =True)

In [ ]:
data_train.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          1
Embarked       0
dtype: int64

In [ ]:
data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        890 non-null    object
 11  Embarked     891 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
import numpy as np
age = data_train["Age"].astype("float").mean(axis=0)
print(age)
data_train["Age"].replace(np.nan,age,inplace = True)
data_train

29.87056116722783

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,C85,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,C123,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,B42,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,26.0,1,2,W./C. 6607,23.4500,C148,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
data_train['Cabin'] = label_encoder.fit_transform(data_train['Cabin'])

data_train

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,81,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,81,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,55,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,55,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,129,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,30,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,30,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,26.0,1,2,W./C. 6607,23.4500,60,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,60,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,147,Q

In [ ]:
data_train.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [ ]:
data_train["Embarked"] = data_train["Embarked"].fillna("C")
data_train.Embarked = data_train.Embarked.replace(["S","C","Q"],[0,1,2])
print(data_train.Embarked)
print(data_train)

0      0
1      1
2      0
3      0
4      0
      ..
886    0
887    0
888    0
889    1
890    2
Name: Embarked, Length: 891, dtype: int64
     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female  26.0      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare  Cabin  Embarked
0        0         A/5 21171   7.2500     81         0
1        0          PC 17599  71.2833     81         1
2        0  STON/O2. 3101282   7.9250     55         0
3        0            113803  53.1000     55         0
4        0            373450   8.0500    129         0
..     ...               ...      ...    ...       ...
886      0            211536  13.0000     30         0
887      0            112053  30.0000     30         0
888      2        W./C. 6607  23.4500     60         0
889      0            111369  30.0000     60         1
890      0            370376   7.7500    147         2

[891 rows x 12 columns]

In [ ]:
data_train.Sex = data_train.Sex.replace(["male","female"],[0,1])
data_train

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,81,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,81,1
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,55,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,55,0
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,129,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",0,27.0,0,0,211536,13.0000,30,0
887,888,1,1,"Graham, Miss. Margaret Edith",1,19.0,0,0,112053,30.0000,30,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",1,26.0,1,2,W./C. 6607,23.4500,60,0
889,890,1,1,"Behr, Mr. Karl Howell",0,26.0,0,0,111369,30.0000,60,1
890,891,0,3,"Dooley, Mr. Patrick",0,32.0,0,0,370376,7.7500,147,2

In [ ]:
data_train = data_train.applymap(lambda x: 1 if x == True else (0 if x == False else x))
data_train

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,81,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,81,1
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,55,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,55,0
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,129,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",0,27.0,0,0,211536,13.0000,30,0
887,888,1,1,"Graham, Miss. Margaret Edith",1,19.0,0,0,112053,30.0000,30,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",1,26.0,1,2,W./C. 6607,23.4500,60,0
889,890,1,1,"Behr, Mr. Karl Howell",0,26.0,0,0,111369,30.0000,60,1
890,891,0,3,"Dooley, Mr. Patrick",0,32.0,0,0,370376,7.7500,147,2

In [ ]:
data_train.drop(['Name','Ticket'],axis=1,inplace=True)
data_train

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
0,1,0,3,0,22.0,1,0,7.2500,81,0
1,2,1,1,1,38.0,1,0,71.2833,81,1
2,3,1,3,1,26.0,0,0,7.9250,55,0
3,4,1,1,1,35.0,1,0,53.1000,55,0
4,5,0,3,0,35.0,0,0,8.0500,129,0
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,0,27.0,0,0,13.0000,30,0
887,888,1,1,1,19.0,0,0,30.0000,30,0
888,889,0,3,1,26.0,1,2,23.4500,60,0
889,890,1,1,0,26.0,0,0,30.0000,60,1
890,891,0,3,0,32.0,0,0,7.7500,147,2

In [ ]:
age1 = data_test["Age"].astype("float").mean(axis=0)
#axis =  0 rows--> but it will reflect in columns
#axis =  1 columns--> but it will reflect in rows
print(age1)
data_test["Age"].replace(np.nan,age1,inplace = True)
data_test

30.272590361445783

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.50000,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.00000,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.00000,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.00000,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.00000,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,30.27259,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.00000,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.50000,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,30.27259,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,30.27259,1,1,2668,22.3583,NaN,C

In [ ]:
data_test["Embarked"] = data_train["Embarked"].fillna("C")
data_test.Embarked = data_train.Embarked.replace(["S","C","Q"],[0,1,2])
print(data_test.Embarked)
print(data_test)

0      0
1      1
2      0
3      0
4      0
      ..
413    0
414    0
415    0
416    0
417    0
Name: Embarked, Length: 418, dtype: int64
     PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James
1            893       3              Wilkes, Mrs. James (Ellen Needs)
2            894       2                     Myles, Mr. Thomas Francis
3            895       3                              Wirz, Mr. Albert
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)
..           ...     ...                                           ...
413         1305       3                            Spector, Mr. Woolf
414         1306       1                  Oliva y Ocana, Dona. Fermina
415         1307       3                  Saether, Mr. Simon Sivertsen
416         1308       3                           Ware, Mr. Frederick
417         1309       3                      Peter, Master. Michael J

        Sex       Age  SibSp  Parch              Ticket      Fare Cabin  \
0      male  34.50000      0      0              330911    7.8292   NaN
1    female  47.00000      1      0              363272    7.0000   NaN
2      male  62.00000      0      0              240276    9.6875   NaN
3      male  27.00000      0      0              315154    8.6625   NaN
4    female  22.00000      1      1             3101298   12.2875   NaN
..      ...       ...    ...    ...                 ...       ...   ...
413    male  30.27259      0      0           A.5. 3236    8.0500   NaN
414  female  39.00000      0      0            PC 17758  108.9000  C105
415    male  38.50000      0      0  SOTON/O.Q. 3101262    7.2500   NaN
416    male  30.27259      0      0              359309    8.0500   NaN
417    male  30.27259      1      1                2668   22.3583   NaN

     Embarked
0           0
1           1
2           0
3           0
4           0
..        ...
413         0
414         0
415         0
416         0
417         0

[418 rows x 11 columns]

In [ ]:
data_test.Sex = data_test.Sex.replace(["male","female"],[0,1])
data_test

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",0,34.50000,0,0,330911,7.8292,NaN,0
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",1,47.00000,1,0,363272,7.0000,NaN,1
2,894,2,"Myles, Mr. Thomas Francis",0,62.00000,0,0,240276,9.6875,NaN,0
3,895,3,"Wirz, Mr. Albert",0,27.00000,0,0,315154,8.6625,NaN,0
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",1,22.00000,1,1,3101298,12.2875,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",0,30.27259,0,0,A.5. 3236,8.0500,NaN,0
414,1306,1,"Oliva y Ocana, Dona. Fermina",1,39.00000,0,0,PC 17758,108.9000,C105,0
415,1307,3,"Saether, Mr. Simon Sivertsen",0,38.50000,0,0,SOTON/O.Q. 3101262,7.2500,NaN,0
416,1308,3,"Ware, Mr. Frederick",0,30.27259,0,0,359309,8.0500,NaN,0
417,1309,3,"Peter, Master. Michael J",0,30.27259,1,1,2668,22.3583,NaN,0

In [ ]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
data_test['Cabin'] = label_encoder.fit_transform(data_test['Cabin'])

data_test

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",0,34.50000,0,0,330911,7.8292,76,0
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",1,47.00000,1,0,363272,7.0000,76,1
2,894,2,"Myles, Mr. Thomas Francis",0,62.00000,0,0,240276,9.6875,76,0
3,895,3,"Wirz, Mr. Albert",0,27.00000,0,0,315154,8.6625,76,0
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",1,22.00000,1,1,3101298,12.2875,76,0
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",0,30.27259,0,0,A.5. 3236,8.0500,76,0
414,1306,1,"Oliva y Ocana, Dona. Fermina",1,39.00000,0,0,PC 17758,108.9000,22,0
415,1307,3,"Saether, Mr. Simon Sivertsen",0,38.50000,0,0,SOTON/O.Q. 3101262,7.2500,76,0
416,1308,3,"Ware, Mr. Frederick",0,30.27259,0,0,359309,8.0500,76,0
417,1309,3,"Peter, Master. Michael J",0,30.27259,1,1,2668,22.3583,76,0

In [ ]:
data_test = data_test.applymap(lambda x: 1 if x == True else (0 if x == False else x))
data_test

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",0,34.50000,0,0,330911,7.8292,76,0
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",1,47.00000,1,0,363272,7.0000,76,1
2,894,2,"Myles, Mr. Thomas Francis",0,62.00000,0,0,240276,9.6875,76,0
3,895,3,"Wirz, Mr. Albert",0,27.00000,0,0,315154,8.6625,76,0
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",1,22.00000,1,1,3101298,12.2875,76,0
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",0,30.27259,0,0,A.5. 3236,8.0500,76,0
414,1306,1,"Oliva y Ocana, Dona. Fermina",1,39.00000,0,0,PC 17758,108.9000,22,0
415,1307,3,"Saether, Mr. Simon Sivertsen",0,38.50000,0,0,SOTON/O.Q. 3101262,7.2500,76,0
416,1308,3,"Ware, Mr. Frederick",0,30.27259,0,0,359309,8.0500,76,0
417,1309,3,"Peter, Master. Michael J",0,30.27259,1,1,2668,22.3583,76,0

In [ ]:
data_test.drop(['Name','Ticket'],axis=1,inplace=True)
data_test

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
0,892,3,0,34.50000,0,0,7.8292,76,0
1,893,3,1,47.00000,1,0,7.0000,76,1
2,894,2,0,62.00000,0,0,9.6875,76,0
3,895,3,0,27.00000,0,0,8.6625,76,0
4,896,3,1,22.00000,1,1,12.2875,76,0
...,...,...,...,...,...,...,...,...,...
413,1305,3,0,30.27259,0,0,8.0500,76,0
414,1306,1,1,39.00000,0,0,108.9000,22,0
415,1307,3,0,38.50000,0,0,7.2500,76,0
416,1308,3,0,30.27259,0,0,8.0500,76,0
417,1309,3,0,30.27259,1,1,22.3583,76,0

In [ ]:
data_train

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
0,1,0,3,0,22.0,1,0,7.2500,81,0
1,2,1,1,1,38.0,1,0,71.2833,81,1
2,3,1,3,1,26.0,0,0,7.9250,55,0
3,4,1,1,1,35.0,1,0,53.1000,55,0
4,5,0,3,0,35.0,0,0,8.0500,129,0
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,0,27.0,0,0,13.0000,30,0
887,888,1,1,1,19.0,0,0,30.0000,30,0
888,889,0,3,1,26.0,1,2,23.4500,60,0
889,890,1,1,0,26.0,0,0,30.0000,60,1
890,891,0,3,0,32.0,0,0,7.7500,147,2

In [ ]:
data_test

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
0,892,3,0,34.50000,0,0,7.8292,76,0
1,893,3,1,47.00000,1,0,7.0000,76,1
2,894,2,0,62.00000,0,0,9.6875,76,0
3,895,3,0,27.00000,0,0,8.6625,76,0
4,896,3,1,22.00000,1,1,12.2875,76,0
...,...,...,...,...,...,...,...,...,...
413,1305,3,0,30.27259,0,0,8.0500,76,0
414,1306,1,1,39.00000,0,0,108.9000,22,0
415,1307,3,0,38.50000,0,0,7.2500,76,0
416,1308,3,0,30.27259,0,0,8.0500,76,0
417,1309,3,0,30.27259,1,1,22.3583,76,0

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

In [ ]:
x = data_train.drop('Survived', axis=1)
y = data_train['Survived']

In [ ]:
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

In [ ]:

x_test_scaled = scaler.transform(data_test)

In [ ]:
# x_train, x_test, y_train, y_test = train_test_split(x_scaled, y, test_size=0.2, random_state=42)

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
# Build the neural network model
model = Sequential()
model.add(Dense(64, input_dim=x_scaled.shape[1], activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [ ]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
model.fit(x_scaled, y, epochs=20, batch_size=32)

Epoch 1/20
28/28 [==============================] - 1s 2ms/step - loss: 0.5912 - accuracy: 0.7048
Epoch 2/20
28/28 [==============================] - 0s 1ms/step - loss: 0.4962 - accuracy: 0.7868
Epoch 3/20
28/28 [==============================] - 0s 1ms/step - loss: 0.4538 - accuracy: 0.7957
Epoch 4/20
28/28 [==============================] - 0s 1ms/step - loss: 0.4336 - accuracy: 0.8081
Epoch 5/20
28/28 [==============================] - 0s 1ms/step - loss: 0.4225 - accuracy: 0.8204
Epoch 6/20
28/28 [==============================] - 0s 1ms/step - loss: 0.4133 - accuracy: 0.8227
Epoch 7/20
28/28 [==============================] - 0s 1ms/step - loss: 0.4071 - accuracy: 0.8272
Epoch 8/20
28/28 [==============================] - 0s 1ms/step - loss: 0.4019 - accuracy: 0.8294
Epoch 9/20
28/28 [==============================] - 0s 3ms/step - loss: 0.3982 - accuracy: 0.8339
Epoch 10/20
28/28 [==============================] - 0s 1ms/step - loss: 0.3928 - accuracy: 0.8440
Epoch 11/20
28/28 [==============================] - 0s 1ms/step - loss: 0.3883 - accuracy: 0.8429
Epoch 12/20
28/28 [==============================] - 0s 2ms/step - loss: 0.3857 - accuracy: 0.8440
Epoch 13/20
28/28 [==============================] - 0s 1ms/step - loss: 0.3822 - accuracy: 0.8406
Epoch 14/20
28/28 [==============================] - 0s 1ms/step - loss: 0.3790 - accuracy: 0.8530
Epoch 15/20
28/28 [==============================] - 0s 1ms/step - loss: 0.3760 - accuracy: 0.8519
Epoch 16/20
28/28 [==============================] - 0s 1ms/step - loss: 0.3752 - accuracy: 0.8507
Epoch 17/20
28/28 [==============================] - 0s 1ms/step - loss: 0.3718 - accuracy: 0.8496
Epoch 18/20
28/28 [==============================] - 0s 1ms/step - loss: 0.3706 - accuracy: 0.8519
Epoch 19/20
28/28 [==============================] - 0s 1ms/step - loss: 0.3679 - accuracy: 0.8530
Epoch 20/20
28/28 [==============================] - 0s 1ms/step - loss: 0.3666 - accuracy: 0.8541

In [ ]:
y_pred = model.predict(x_test_scaled)
y_pred_binary = np.round(y_pred).astype("int").flatten()
y_pred_binary
# accuracy = accuracy_score(y_test, y_pred_binary)
# print(f"Accuracy on the test set: {accuracy}")

14/14 [==============================] - 0s 2ms/step

array([                   0,                    0,                    0,
                          0,                    0,                    0,
                          0,                    0,                    1,
                          0,                    0,                    0,
                          1,                    0,                    1,
                          1,                    0,                    0,
                          0,                    0,                    0,
                          0,                    1,                    1,
                          1,                    0,                    1,
                          0,                    1,                    0,
                          0,                    0,                    0,
                          0,                    1,                    0,
                          1,                    1,                    0,
                          0,                    0,                    0,
                          0,                    1,                    1,
                          0,                    1,                    0,
                          1,                    0,                    1,
                          0,                    1,                    1,
                          0,                    0,                    0,
                          0,                    0,                    1,
                          0,                    0,                    0,
                          0,                    1,                    1,
                          1,                    0,                    0,
                          1,                    0,                    0,
                          0,                    1,                    1,
                          1,                    0,                    1,
                          0,                    0,                    0,
                          1,                    0,                    0,
                          0,                    0,                    0,
                          1,                    0,                    1,
                          0,                    0,                    1,
                          0,                    1,                    0,
                          1,                    0,                    1,
                          0,                    1,                    0,
                          0,                    0,                    0,
                          0,                    0,                    0,
                          0,                    0,                    0,
                          1,                    1,                    1,
                          1,                    0,                    0,
                          1,                    1,                    1,
                          1,                    0,                    1,
                          0,                    0,                    1,
                          0,                    0,                    0,
                          0,                    0,                    0,
                          0,                    0,                    0,
                          0,                    0,                    0,
                          0,                    0,                    0,
                          1,                    0,                    0,
                          0,                    0,                    1,
                          0,                    0,                    0,
                          1,                    0, -9223372036854775808,
                          0,                    0,                    0,
                          1,                    0,                    0,
                          1,                    0,                    0,
                          1,                    0,                    0,
                          0,                    0,                    0,
                          1,                    0,                    0,
                          0,                    0,                    0,
                          0,                    1,                    1,
                          1,                    1,                    1,
                          0,                    1,                    1,
                          0,                    1,                    0,
                          1,                    0,                    0,
                          0,                    0,                    0,
                          0,                    0,                    1,
                          0,                    1,                    1,
                          0,                    0,                    0,
                          1,                    1,                    1,
                          0,                    0,                    0,
                          0,                    1,                    0,
                          0,                    0,                    1,
                          1,                    0,                    1,
                          0,                    1,                    1,
                          0,                    1,                    0,
                          1,                    0,                    1,
                          0,                    0,                    0,
                          0,                    0,                    1,
                          1,                    0,                    0,
                          0,                    0,                    0,
                          0,                    1,                    1,
                          1,                    1,                    1,
                          0,                    0,                    1,
                          1,                    0,                    1,
                          0,                    1,                    0,
                          1,                    0,                    0,
                          0,                    0,                    0,
                          1,                    0,                    0,
                          0,                    1,                    1,
                          0,                    0,                    0,
                          0,                    0,                    0,
                          0,                    0,                    1,
                          0,                    0,                    1,
                          0,                    0,                    0,
                          0,                    1,                    0,
                          0,                    1,                    1,
                          0,                    0,                    1,
                          0,                    0,                    1,
                          0,                    0,                    0,
                          0,                    0,                    1,
                          0,                    1,                    0,
                          0,                    0,                    0,
                          0,                    0,                    1,
                          1,                    1,                    1,
                          0,                    0,                    0,
                          0,                    0,                    1,
                          0,                    1,                    0,
                          0,                    0,                    0,
                          0,                    0,                    0,
                          1,                    0,                    1,
                          0,                    0,                    0,
                          1,                    0,                    0,
                          0,                    0,                    0,
                          0,                    0,                    0,
                          0,                    0,                    0,
                          0,                    1,                    0,
                          0,                    0,                    0,
                          0,                    1,                    1,
                          0,                    1,                    0,
                          1,                    0,                    1,
                          0,                    0,                    0,
                          0,                    1,                    1,
                          0,                    1,                    0,
                          0,                    1,                    1,
                          0,                    0,                    1,
                          0,                    0,                    1,
                          1,                    0,                    0,
                          0,                    0,                    0,
                          0,                    0,                    0,
                          0,                    1,                    0,
                          0,                    0,                    0,
                          1,                    1,                    0,
                          0,                    0,                    1,
                          0,                    1,                    0,
                          0,                    1,                    0,
                          1,                    1,                    0,
                          0,                    0,                    1,
                          0,                    1,                    0,
                          1,                    1,                    0,
                          1,                    0,                    0,
                          0])

In [ ]:
final = pd.DataFrame({'PassengerId':data_test["PassengerId"],'Survived':y_pred_binary})
final.head(20)

    PassengerId  Survived
0           892         0
1           893         0
2           894         0
3           895         0
4           896         0
5           897         0
6           898         0
7           899         0
8           900         1
9           901         0
10          902         0
11          903         0
12          904         1
13          905         0
14          906         1
15          907         1
16          908         0
17          909         0
18          910         0
19          911         0

In [ ]:
final.to_csv('gender_submission',index=False)

In [ ]:
from google.colab import files
files.download('/content/gender_submission.csv')